export const THEMES = [
  "light",
  "dark", //
  // "cupcake",
  // "bumblebee",
  // "emerald",
  // "corporate",
  // "synthwave",
  // "retro",
  // "cyberpunk",
  // "valentine",
  // "halloween",
  // "garden",
  // "forest",
  // "aqua",
  // "lofi",
  // "pastel",
  // "fantasy",
  // "wireframe",
  "black",
  // "luxury",
  // "dracula",
  // "cmyk",
  // "autumn",
  // "business",
  // "acid",
  // "lemonade",
  // "night",
  // "coffee",
  // "winter",
  // "dim",
  // "nord",
  // "sunset"

  //here i chose only three light, dark, and black themes you can choose any of the above themes
];
